---
vpn_static_server:
COUNTRY:  "{{ lookup('file', '/etc/vpnconf/COUNTRY') }}"
PROVINCE:  "{{ lookup('file', '/etc/vpnconf/PROVINCE') }}"
CITY: "{{ lookup('file', '/etc/vpnconf/CITY') }}"
ORGANISATION: "{{ lookup('file', '/etc/vpnconf/ORGANISATION') }}"
EMAIL:  "{{ lookup('file', '/etc/vpnconf/EMAIL') }}"
ip_client:  "{{ lookup('file', '/home/cloud/ip_client') }}"
client_cidr: "{{ lookup('file', '/home/cloud/client_cidr.tmp') }}"
server_cidr: "{{ lookup('file', '/home/cloud/server_cidr.tmp') }}"
