heat_template_version: 2013-05-23

parameters:
  image:
    type: string
    description: Glance Image
    default: "Ubuntu 14.04"

  flavor:
    type: string
    description: Flavor
    default: t1.cw.tiny

  keypair_name:
    type: string
    description: SSH key
    default: mickael

  public_net_id:
    type: string
    description: Public network ID
    default: 6ea98324-0f14-49f6-97c0-885d1b8dc517

resources:

  internal_net:
    type: OS::Neutron::Net

  internal_snet:
    type: OS::Neutron::Subnet
    properties:
      cidr: "10.1.1.0/24"
      network_id: { get_resource: internal_net }


  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress, protocol: TCP, port_range_min: 22, port_range_max: 22 }
        - { direction: ingress, protocol: TCP, port_range_min: 80, port_range_max: 80 }
        - { direction: ingress, protocol: TCP, port_range_min: 443, port_range_max: 443 }
        - { direction: ingress, protocol: ICMP }
        - { direction: egress, protocol: ICMP }
        - { direction: egress, protocol: TCP }
        - { direction: egress, protocol: UDP }

  router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      external_gateway_info:
        enable_snat: true
        network: "public"

  router_interface01:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource : router }
      subnet_id: { get_resource : internal_snet }


  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: public_net_id}
      port_id: {get_attr: [vpn_lb_pool, vip, port_id]}

  floating_ip2:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: public_net_id}

  floating_ip_link:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip2 }
      server_id: { get_resource: server }

  stack_public_entry_point:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /etc/stack_public_entry_point
          permissions: '0755'
          content:
            str_replace:
              template: |
                $floating_ip$
              params:
                $floating_ip$: { get_attr: [floating_ip2, floating_ip_address] }

  server_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: { get_resource: stack_public_entry_point }

  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: {get_resource: internal_net}
      security_groups:
        - { get_resource: security_group }
      user_data_format: RAW
      user_data:
        get_resource: server_init

  vpn_lb_pool:
    type: OS::Neutron::Pool
    properties:
      protocol: TCP
      subnet_id: {get_resource: internal_snet}
      lb_method: ROUND_ROBIN
      vip:
        protocol_port: 1194

  vpn_lb_lb:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: 1194
      pool_id: {get_resource: vpn_lb_pool}

  vpn_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          port_range_min: 1194
          port_range_max: 1194

  vpn_asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 2
      max_size: 5
      resource:
        type: srv_vpn.yaml
        properties:
          lb_pool: {get_resource: vpn_lb_pool}
          lb_port: 1194
          flavor: {get_param: flavor}
          image: {get_param: image}
          key_name: {get_param: keypair_name}
          network_id: {get_resource: internal_net}
          security_groups:
            - {get_resource: vpn_secgroup}

  vpn_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: vpn_asg}
      cooldown: 60
      scaling_adjustment: 1

  vpn_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: vpn_asg}
      cooldown: 60
      scaling_adjustment: -1

outputs:
  wp_floating_url:
    value:
      str_replace:
        template: http://HOST/
        params:
          HOST: {get_attr: [floating_ip, floating_ip_address]}

  vpn_vip:
    value: {get_attr: [vpn_lb_pool, vip, address]}

  vpn_scale_up:
    value: {get_attr: [vpn_scaleup_policy, alarm_url]}

  vpn_scale_down:
    value: {get_attr: [vpn_scaledown_policy, alarm_url]}

  first_address:
    description: IP address of the first interface
    value: {get_attr:  [server, first_address]}

  server_id:
    description: ID of the instance
    value: {get_resource: instance}
