---
    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - apache2
        - wordpress
    - name: apache service started
      service: name=apache2 state=started

    - name: apache service enabled
      service: name=apache2 enabled=yes

    - name: apache site configuration
      copy:
        src=wordpress.apache2.conf
        dest=/etc/apache2/sites-available/default-wp.conf
        owner=root
        group=root
        mode=0644
      notify: enable apache site

    - name: wordpress site configuration
      template:
        src=wordpress.etc.conf
        dest=/etc/wordpress/config-default.php
        owner=www-data
        group=www-data
        mode=0644

    - name: wordpress content has correct ownership
      file:
        path="{{ item }}"
        state=directory
        owner=www-data
        group=www-data
        recurse=yes
      with_items:
        - /var/lib/wordpress/wp-content
        - /usr/share/wordpress/wp-content

    - name: Rewrite module activated
      apache2_module:
        name=rewrite
        state=present

    - name: apache service started
      service: name=apache2 state=started enabled=yes
