---

- name: GitLab - packages installed
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - curl
    - openssh-server
    - python-httplib2
    - ca-certificates
    - apt-transport-https

- name: GitLab - get hostname
  uri:
    url=http://169.254.169.254/latest/meta-data/hostname
    return_content=yes
  register: hostname

- name: GitLab - set postfix hostname
  debconf:
    name=postfix
    question='postfix/mailname'
    value="{{ hostname.content }}"
    vtype='string'

- name: GitLab - set postfix mailer type
  debconf:
    name=postfix
    question='postfix/main_mailer_type'
    value="Internet Site"
    vtype='string'

- name: GitLab - postfix installed
  apt: pkg=postfix state=present

- name: GitLab - apt repository installed
  apt_repository:
    repo='deb https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_lsb.id | lower }}/ {{ ansible_lsb.codename }} main'
    state=present

- name: GitLab - apt repository key is trusted
  apt_key:
    url=https://packages.gitlab.com/gpg.key
    state=present

- name: GitLab - gitlab-ce installed
  apt: update_cache=yes pkg=gitlab-ce state=present

- name: GitLab - gitlab.rb - logrotate+nginx disabled/www-data user rights
  lineinfile:
    dest=/etc/gitlab/gitlab.rb
    line="{{ item }}"
    insertafter=EOF
  with_items:
    - "logrotate['enable'] = false"
    - "nginx['enable'] = false"
    - "web_server['external_users'] = ['www-data']"

- name: GitLab - gitlab-ce configured
  shell: sudo gitlab-ctl reconfigure
  register: result
  until: result|success
  retries: 10
  delay: 2
