heat_template_version: 2013-05-23


description: Virtual Private Network Stack


parameters:

  COUNTRY:
    description: COUNTRY for the VPN certificate
    label: certificate VPN COUNTRY
    type: string
    hidden: true
    constraints:
      - length: { min: 1, max: 2 }
        description: COUNTRY must be between 1 and 2 characters

  PROVINCE:
    description: PROVINCE for the VPN certificate
    label: certificate VPN PROVINCE
    type: string
    hidden: true
    constraints:
      - length: { min: 1, max: 40 }
        description: PROVINCE must be between 1 and 40 characters

  CITY:
    description: CITY for the VPN certificate
    label: certificate VPN CITY
    type: string
    hidden: true
    constraints:
      - length: { min: 1, max: 40 }
        description: CITY must be between 1 and 40 characters

  ORGANISATION:
    description: ORGANISATION for the VPN certificate
    label: certificate VPN ORGANISATION
    type: string
    hidden: true
    constraints:
      - length: { min: 1, max: 40 }
        description: ORGANISATION must be between 1 and 40 characters

  EMAIL:
    description: EMAIL for the VPN certificate
    label: certificate VPN EMAIL
    type: string
    hidden: true
    constraints:
      - length: { min: 1, max: 40 }
        description:  EMAIL must be between 1 and 40 characters


  image:
    type: string
    description: Glance Image
    default: "Ubuntu 14.04"

  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string
    default: mickael

  flavor_name:
    default: s1.cw.small-1
    description: Flavor to use for the deployed instance
    type: string
    label: Instance Type (Flavor)
    constraints:
      - allowed_values:
          - s1.cw.small-1
          - n1.cw.standard-1
          - n1.cw.standard-2
          - n1.cw.standard-4
          - n1.cw.standard-8
          - n1.cw.standard-12
          - n1.cw.standard-16

resources:
  key_add:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: cloud_pub
        - name: cloud
      outputs:
        - name: hostname
      group: script
      config:  |
        #!/bin/bash
        echo "${cloud_pub}" | su - $cloud -c 'tee -a .ssh/authorized_keys'
        hostname > ${heat_outputs_path}.hostname

  key_gen:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: cloud
      outputs:
        - name: cloud_pub
      group: script
      config:  |
        #!/bin/bash
        su - ${user_name} << EOF > ${heat_outputs_path}.cloud_pub
        test -f .ssh/cloud.pub || ssh-keygen -q -t rsa -N "" -f .ssh/cloud_pub
        cat .ssh/cloud_pub.pub
        EOF

  do_key_gen:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        user_name: cloud
      config:
        get_resource: key_gen
      server:
        get_resource: server

  do_key_add:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        user_name: cloud
        id_rsa_pub:
          get_attr: [do_key_gen, cloud_pub]
      config:
        get_resource: key_add
      server:
        get_resource: client

  network:
    type: OS::Neutron::Net

  network2:
    type: OS::Neutron::Net


  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      ip_version: 4
      cidr: 10.0.1.0/24
      allocation_pools:
        - { start: 10.0.1.100, end: 10.0.1.199 }
      host_routes:
        - { destination: 10.0.1.0/24, nexthop: 10.0.1.1 }
        - { destination: 10.0.1.0/24, nexthop: 10.0.1.100 }
        - { destination: 169.254.0.0/16, nexthop: 10.0.1.1 }

  subnet2:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network2 }
      ip_version: 4
      cidr: 10.1.1.0/24
      allocation_pools:
        - { start: 10.1.1.100, end: 10.1.1.199 }
      host_routes:
        - { destination: 10.1.1.0/24, nexthop: 10.1.1.1 }
        - { destination: 10.1.1.0/24, nexthop: 10.1.1.100 }
        - { destination: 169.254.0.0/16, nexthop: 10.1.1.1 }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress, protocol: TCP, port_range_min: 22, port_range_max: 22 }
        - { direction: ingress, protocol: TCP, port_range_min: 80, port_range_max: 80 }
        - { direction: ingress, protocol: TCP, port_range_min: 443, port_range_max: 443 }
        - { direction: ingress, protocol: UDP, port_range_min: 1194, port_range_max: 1194 }
        - { direction: ingress, protocol: ICMP }
        - { direction: egress, protocol: ICMP }
        - { direction: egress, protocol: TCP }
        - { direction: egress, protocol: UDP }
        - { direction: egress, protocol: UDP, port_range_min: 1194, port_range_max: 1194 }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 6ea98324-0f14-49f6-97c0-885d1b8dc517

  floating_ip2:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 6ea98324-0f14-49f6-97c0-885d1b8dc517

  floating_ip_link:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: server }

  floating_ip_link2:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip2 }
      server_id: { get_resource: client }



  serverlanserver:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: { get_param: image }
      flavor: { get_param: flavor_name }
      networks:
        - network: {get_resource: network}
      security_groups:
        - { get_resource: security_group }

  serverlanclient:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: { get_param: image }
      flavor: { get_param: flavor_name }
      networks:
        - network: {get_resource: network2}
      security_groups:
        - { get_resource: security_group }



  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image:  { get_param: image }
      flavor: { get_param: flavor_name }
      networks:
        - network: { get_resource: network }
      security_groups:
        - { get_resource: security_group }
      user_data_format: SOFTWARE_CONFIG
      user_data:
        str_replace:
          template: |
            #!/usr/bin/env bash
            sudo mkdir /etc/vpnconf/
            echo -n "$ip_client$" >> /home/cloud/ip_client
            echo -n "$Keypair$" >> /home/cloud/.ssh/key.pem
            echo -n "$COUNTRY$" >> /etc/vpnconf/COUNTRY
            echo -n "$PROVINCE$" >> /etc/vpnconf/PROVINCE
            echo -n "$CITY$" >> /etc/vpnconf/CITY
            echo -n "$ORGANISATION$" >> /etc/vpnconf/ORGANISATION
            echo -n "$EMAIL$" >> /etc/vpnconf/EMAIL
            echo "$(date) - START" >> /var/log/vpn_srv.log
            export DEBIAN_FRONTEND=noninteractive
            apt-get update 2>&1 >> /var/log/vpn_srv.log
            echo "$(date) - update done" >> /var/log/vpn_srv.log
            apt-get -o Dpkg::Options::="--force-confold" upgrade -y 2>&1 >> /var/log/vpn_srv.log
            echo "$(date) - upgrade done" >> /var/log/vpn_srv.log
            apt-get -o Dpkg::Options::="--force-confold" install openvpn -y 2>&1 >> /var/log/vpn_srv.log
            echo "$(date) - openvpn done" >> /var/log/vpn_srv.log
            mkdir /etc/ansible
            echo "[local]" >> /etc/ansible/hosts
            echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
            ssh-keygen -t rsa
            cd /home/cloud/
            git clone  https://github.com/mickaelremilien/CLOUDPATT.git
            sudo ansible-playbook /home/cloud/CLOUDPATT/image-factory/bundle-trusty-vpn/ansible/bootstrap2server.yml
          params:
            $COUNTRY$: { get_param: COUNTRY }
            $PROVINCE$: { get_param: PROVINCE }
            $CITY$: { get_param: CITY }
            $ORGANISATION$: { get_param: ORGANISATION }
            $EMAIL$:  { get_param: EMAIL }
            $ip_client$: { get_attr: [floating_ip2, floating_ip_address] }
            $Keypair$: {get_param: keypair_name }

  client:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image:  { get_param: image }
      flavor: { get_param: flavor_name }
      networks:
        - network: { get_resource: network2 }
      security_groups:
        - { get_resource: security_group }
      user_data_format: SOFTWARE_CONFIG
      user_data:
        str_replace:
          template: |
            #!/usr/bin/env bash
            echo -n "$ip_server$" >> /home/cloud/ip_server
            echo "$(date) - START" >> /var/log/vpn_srv.log
            echo -n "$Keypair$" >> /home/cloud/.ssh/key.pem
            export DEBIAN_FRONTEND=noninteractive
            apt-get update 2>&1 >> /var/log/vpn_client.log
            echo "$(date) - update done" >> /var/log/vpn_client.log
            apt-get -o Dpkg::Options::="--force-confold" upgrade -y 2>&1 >> /var/log/vpn_client.log
            echo "$(date) - upgrade done" >> /var/log/vpn_client.log
            apt-get -o Dpkg::Options::="--force-confold" install openvpn -y 2>&1 >> /var/log/vpn_client.log
            echo "$(date) - openvpn done" >> /var/log/vpn_client.log
            mkdir /etc/ansible
            echo "[local]" >> /etc/ansible/hosts
            echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
            cd /home/cloud/
            git clone  https://github.com/mickaelremilien/CLOUDPATT.git
            sudo ansible-playbook /home/cloud/CLOUDPATT/image-factory/bundle-trusty-vpn/ansible/bootstrap2client.yml
          params:
            $ip_server$: { get_attr: [floating_ip, floating_ip_address] }
            $Keypair$: {get_param: keypair_name }



outputs:
  floating_ip:
    description: IP address of the deployed compute server
    value: { get_attr: [floating_ip, floating_ip_address] }

  floating_ip2:
    description: IP address of the deployed compute client
    value: { get_attr: [floating_ip2, floating_ip_address] }

  server_id:
    description: ID of the server
    value: {get_resource: server}
