- hosts: local
  user: cloud
  become: yes

  vars:
    vpn_static:

    - name: apply common configuration to all nodes
      hosts: 10.1.2.4
      roles:
        - wordpress_my1

    - name: apply common configuration to all nodes
      hosts: 10.1.2.5
      roles:
        - wordpress_my2

    - name: apply common configuration to all nodes
      hosts: 10.1.2.6
      roles:
        - wordpress_my3

  #roles:
  #  - { role: wordpress_my1, when: ansible_default_ipv4.address == "10.1.2.4" }
  #  - { role: wordpress_my2, when: ansible_default_ipv4.address == "10.1.2.5" }
  #  - { role: wordpress_my3, when: ansible_default_ipv4.address == "10.1.2.6" }
