- hosts: local
  user: cloud
  sudo: true

  vars:
   wp_db_pass: "{{ lookup('password', '/tmp/keystore chars=ascii_letters,digits,hexdigits,punctuation') }}"
   wp_mysql_ip: "{{ lookup('file', '/home/cloud/sql_ip_bind') }}"
  tasks:
    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - mysql-server
        - python-mysqldb

    - name: mysql database is created
      mysql_db:
        name=wordpress
        state=present

    - name: mysql configuration binding
      lineinfile:
        backup=yes
        state=present
        dest=/etc/mysql/my.cnf
        regexp='bind-address            = 127.0.0.1'
        line='bind-address            ={{ wp_mysql_ip }}'

    - name: mysql user is created
      mysql_user:
        name=wordpress
        password="{{ wp_db_pass }}"
        priv="wordpress.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
        state=present

    - name: mysql started
      service: name=mysql state=started enabled=yes

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted enabled=yes
