- hosts: local
  user: cloud
  sudo: true

  vars:
   wp_db_pass: "{{ lookup('password', '/home/cloud/mysqlpwd') }}"

  tasks:
    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - mysql-server
        - python-mysqldb

    - name: mysql database is created
      mysql_db:
        name=wordpress
        state=present

    - name: mysql configuration binding
      replace:
        dest=/etc/mysql/my.cnf
        regexp='^bind-address.*$'
        replace="bind-address = {{ ansible_default_ipv4.address }}"

    - name: mysql user is created
      mysql_user:
        name=wordpress
        host="10.1.1.4"
        password="{{ wp_db_pass }}"
        priv=wordpress.*:ALL
        state=present

    - name: mysql usertest is created
      mysql_user:
        name=wordpress
        host="10.1.2.2"
        password="{{ wp_db_pass }}"
        priv=wordpress.*:ALL
        state=present
    - name: mysql user2 is created
      mysql_user:
        name=wordpress
        host="10.1.1.5"
        password="{{ wp_db_pass }}"
        priv=wordpress.*:ALL
        state=present

    - name: mysql started
      service: name=mysql state=restarted enabled=yes

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted enabled=yes
