- hosts: local
  user: cloud
  sudo: true

  vars:
    wp_db_pass: "{{ lookup('password', '/root/keystore chars=ascii_letters,digits,hexdigits,punctuation') }}"

  tasks:
     
    - name: mysql database is created
      mysql_db:
        name=wordpress
        state=present

    - name: mysql user is created
      mysql_user:
        name=wordpress
        password="{{ wp_db_pass }}"
        priv="wordpress.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
        state=present
