- hosts: local
  user: cloud
  sudo: true

  vars:
   wp_db_pass: "{{ lookup('file', '/home/cloud/mysqlpwd') }}"

  tasks:
    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - mysql-server
        - python-mysqldb
        
    - name: mysql userroot is created
      mysql_user:
        name=root
        host="127.0.0.1"
        password="rootroot"
        priv=*.*:ALL
        state=present

    - name: mysql started
      service: name=mysql state=restarted enabled=yes

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted enabled=yes
