- hosts: local
  user: cloud
  sudo: true

  tasks:
    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - mysql-server
        - python-mysqldb

    - name: mysql database is created
      mysql_db:
        name=wordpress
        state=present

    - name: mysql user is created
      mysql_user:
        name=wordpress
        password="CLOUDPASS"
        priv="wordpress.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
        state=present

    - name: mysql started
      service: name=mysql state=started enabled=yes

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted enabled=yes
